# Detect missing values in a dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
college = pd.read_csv('college.csv')
college.head()

   gradrat   lenroll  rmbrd  private  stufac   csat   act
0     56.2  4.155045   2.84      0.0    22.5  539.8  16.2
1     96.6  5.594064   3.06      0.0    15.6  833.4  17.9
2     81.2  5.621905   2.85      0.0    23.8  789.4  22.8
3     71.9  5.912290   2.68      1.0    21.0  896.2  24.6
4     40.9  6.178274   2.74      0.0    25.0  596.4  28.0

In [3]:
college.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   gradrat  300 non-null    float64
 1   lenroll  300 non-null    float64
 2   rmbrd    300 non-null    float64
 3   private  300 non-null    float64
 4   stufac   300 non-null    float64
 5   csat     187 non-null    float64
 6   act      300 non-null    float64
dtypes: float64(7)
memory usage: 16.5 KB

In [4]:
csat_unique = college.csat.unique()
np.sort(csat_unique)

array([ 510.3,  512.1,  513.3,  521.1,  528.4,  539.8,  542.3,  545.8,
        547.5,  564. ,  564.4,  568.5,  571.3,  575. ,  579.3,  584.8,
        589. ,  593.3,  596.4,  602.3,  608.2,  609.1,  616.2,  633.5,
        633.7,  644.9,  645.8,  650.8,  661. ,  662.2,  663.8,  665.1,
        676.1,  691.5,  695.2,  703.7,  714.1,  717.2,  722.7,  729.4,
        736.7,  737.6,  747.1,  763.1,  764.8,  765.3,  771.3,  780.1,
        785.8,  789.4,  791.6,  814.5,  822.1,  825. ,  827.3,  833.4,
        835.1,  836.1,  836.2,  836.9,  846.9,  861. ,  867.7,  872.1,
        891. ,  896.2,  904.7,  909.4,  913.5,  918.7,  920.1,  930.7,
        933.9,  941.6,  943.3,  953.9,  955.5,  957.8,  968.7,  977.4,
        981.4,  983.3,  983.5,  991.9, 1005.4, 1006.6, 1007.6, 1023.6,
       1029.1, 1036.6, 1037.1, 1046.7, 1048.1, 1056.4, 1056.8, 1059.2,
       1069. , 1070.2, 1079.7, 1088.8, 1102.8, 1104.5, 1109.2, 1110.6,
       1116.7, 1121.5, 1138. , 1140.7, 1152.3, 1160.7, 1162.1, 1163.8,
       1166.9, 1175.3, 1176.7, 1181.5, 1186.3, 1199.9, 1204.9, 1205.1,
       1208.3, 1210.4, 1215.2, 1226.3, 1227.5, 1244.1, 1256.9, 1261.4,
       1264.4, 1265.2, 1278.4, 1288. , 1294.3, 1298.6, 1299.1, 1301.3,
       1306.4, 1311.1, 1311.3, 1330.5, 1336.3, 1337.2, 1340.8, 1341.3,
       1346.1, 1346.2, 1362.2, 1363.4, 1363.5, 1378.6, 1381.7, 1386.5,
       1392.9, 1395.4, 1397.5, 1399.6, 1410.3, 1424.8, 1425. , 1426.2,
       1428.8, 1431.2, 1447.5, 1454.9, 1464.3, 1474.8, 1481.3, 1511.3,
       1515. , 1523.7, 1530.7, 1531.1, 1537.4, 1550.9, 1552.2, 1555.5,
       1559.4, 1582. , 1583.1, 1591. , 1591.4, 1594.4, 1596. , 1596.4,
          nan])

In [5]:
college = pd.read_csv('college.csv', na_values='.')
college.head()

   gradrat   lenroll  rmbrd  private  stufac   csat   act
0     56.2  4.155045   2.84      0.0    22.5  539.8  16.2
1     96.6  5.594064   3.06      0.0    15.6  833.4  17.9
2     81.2  5.621905   2.85      0.0    23.8  789.4  22.8
3     71.9  5.912290   2.68      1.0    21.0  896.2  24.6
4     40.9  6.178274   2.74      0.0    25.0  596.4  28.0

In [6]:
college.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   gradrat  300 non-null    float64
 1   lenroll  300 non-null    float64
 2   rmbrd    300 non-null    float64
 3   private  300 non-null    float64
 4   stufac   300 non-null    float64
 5   csat     187 non-null    float64
 6   act      300 non-null    float64
dtypes: float64(7)
memory usage: 16.5 KB

In [7]:
diabetes = pd.read_csv('diabetes.csv')
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [9]:
diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [10]:
diabetes.loc[diabetes['BMI'] == 0, 'BMI']

9      0.0
49     0.0
60     0.0
81     0.0
145    0.0
371    0.0
426    0.0
494    0.0
522    0.0
684    0.0
706    0.0
Name: BMI, dtype: float64

In [11]:
diabetes.loc[diabetes['BMI'] == 0, 'BMI'] = np.nan

In [12]:
diabetes.loc[diabetes['BMI'].isna(), 'BMI']

9     NaN
49    NaN
60    NaN
81    NaN
145   NaN
371   NaN
426   NaN
494   NaN
522   NaN
684   NaN
706   NaN
Name: BMI, dtype: float64

In [13]:
diabetes['BMI'].fillna(diabetes['BMI'].mean())

0      33.6
1      26.6
2      23.3
3      28.1
4      43.1
       ...
763    32.9
764    36.8
765    26.2
766    30.1
767    30.4
Name: BMI, Length: 768, dtype: float64

In [14]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer()
imputer.fit_transform(diabetes[['BMI']])

array([[33.6       ],
       [26.6       ],
       [23.3       ],
       [28.1       ],
       [43.1       ],
       [25.6       ],
       [31.        ],
       [35.3       ],
       [30.5       ],
       [32.45746367],
       [37.6       ],
       [38.        ],
       [27.1       ],
       [30.1       ],
       [25.8       ],
       [30.        ],
       [45.8       ],
       [29.6       ],
       [43.3       ],
       [34.6       ],
       [39.3       ],
       [35.4       ],
       [39.8       ],
       [29.        ],
       [36.6       ],
       [31.1       ],
       [39.4       ],
       [23.2       ],
       [22.2       ],
       [34.1       ],
       [36.        ],
       [31.6       ],
       [24.8       ],
       [19.9       ],
       [27.6       ],
       [24.        ],
       [33.2       ],
       [32.9       ],
       [38.2       ],
       [37.1       ],
       [34.        ],
       [40.2       ],
       [22.7       ],
       [45.4       ],
       [27.4       ],
       [42.        ],
       [29.7       ],
       [28.        ],
       [39.1       ],
       [32.45746367],
       [19.4       ],
       [24.2       ],
       [24.4       ],
       [33.7       ],
       [34.7       ],
       [23.        ],
       [37.7       ],
       [46.8       ],
       [40.5       ],
       [41.5       ],
       [32.45746367],
       [32.9       ],
       [25.        ],
       [25.4       ],
       [32.8       ],
       [29.        ],
       [32.5       ],
       [42.7       ],
       [19.6       ],
       [28.9       ],
       [32.9       ],
       [28.6       ],
       [43.4       ],
       [35.1       ],
       [32.        ],
       [24.7       ],
       [32.6       ],
       [37.7       ],
       [43.2       ],
       [25.        ],
       [22.4       ],
       [32.45746367],
       [29.3       ],
       [24.6       ],
       [48.8       ],
       [32.4       ],
       [36.6       ],
       [38.5       ],
       [37.1       ],
       [26.5       ],
       [19.1       ],
       [32.        ],
       [46.7       ],
       [23.8       ],
       [24.7       ],
       [33.9       ],
       [31.6       ],
       [20.4       ],
       [28.7       ],
       [49.7       ],
       [39.        ],
       [26.1       ],
       [22.5       ],
       [26.6       ],
       [39.6       ],
       [28.7       ],
       [22.4       ],
       [29.5       ],
       [34.3       ],
       [37.4       ],
       [33.3       ],
       [34.        ],
       [31.2       ],
       [34.        ],
       [30.5       ],
       [31.2       ],
       [34.        ],
       [33.7       ],
       [28.2       ],
       [23.2       ],
       [53.2       ],
       [34.2       ],
       [33.6       ],
       [26.8       ],
       [33.3       ],
       [55.        ],
       [42.9       ],
       [33.3       ],
       [34.5       ],
       [27.9       ],
       [29.7       ],
       [33.3       ],
       [34.5       ],
       [38.3       ],
       [21.1       ],
       [33.8       ],
       [30.8       ],
       [28.7       ],
       [31.2       ],
       [36.9       ],
       [21.1       ],
       [39.5       ],
       [32.5       ],
       [32.4       ],
       [32.8       ],
       [32.45746367],
       [32.8       ],
       [30.5       ],
       [33.7       ],
       [27.3       ],
       [37.4       ],
       [21.9       ],
       [34.3       ],
       [40.6       ],
       [47.9       ],
       [50.        ],
       [24.6       ],
       [25.2       ],
       [29.        ],
       [40.9       ],
       [29.7       ],
       [37.2       ],
       [44.2       ],
       [29.7       ],
       [31.6       ],
       [29.9       ],
       [32.5       ],
       [29.6       ],
       [31.9       ],
       [28.4       ],
       [30.8       ],
       [35.4       ],
       [28.9       ],
       [43.5       ],
       [29.7       ],
       [32.7       ],
       [31.2       ],
       [67.1       ],
       [45.        ],
       [39.1       ],
       [23.2       ],
       [34.9       ],
       [27.7       ],
       [26.8       ],
       [27.6       ],
       [35.9       ],
       [30.1       ],
       [32.        ],
       [27.9       ],
       [31.6       ],
       [22.6       ],
       [33.1       ],
       [30.4       ],
       [52.3       ],
       [24.4       ],
       [39.4       ],
       [24.3       ],
       [22.9       ],
       [34.8       ],
       [30.9       ],
       [31.        ],
       [40.1       ],
       [27.3       ],
       [20.4       ],
       [37.7       ],
       [23.9       ],
       [37.5       ],
       [37.7       ],
       [33.2       ],
       [35.5       ],
       [27.7       ],
       [42.8       ],
       [34.2       ],
       [42.6       ],
       [34.2       ],
       [41.8       ],
       [35.8       ],
       [30.        ],
       [29.        ],
       [37.8       ],
       [34.6       ],
       [31.6       ],
       [25.2       ],
       [28.8       ],
       [23.6       ],
       [34.6       ],
       [35.7       ],
       [37.2       ],
       [36.7       ],
       [45.2       ],
       [44.        ],
       [46.2       ],
       [25.4       ],
       [35.        ],
       [29.7       ],
       [43.6       ],
       [35.9       ],
       [44.1       ],
       [30.8       ],
       [18.4       ],
       [29.2       ],
       [33.1       ],
       [25.6       ],
       [27.1       ],
       [38.2       ],
       [30.        ],
       [31.2       ],
       [52.3       ],
       [35.4       ],
       [30.1       ],
       [31.2       ],
       [28.        ],
       [24.4       ],
       [35.8       ],
       [27.6       ],
       [33.6       ],
       [30.1       ],
       [28.7       ],
       [25.9       ],
       [33.3       ],
       [30.9       ],
       [30.        ],
       [32.1       ],
       [32.4       ],
       [32.        ],
       [33.6       ],
       [36.3       ],
       [40.        ],
       [25.1       ],
       [27.5       ],
       [45.6       ],
       [25.2       ],
       [23.        ],
       [33.2       ],
       [34.2       ],
       [40.5       ],
       [26.5       ],
       [27.8       ],
       [24.9       ],
       [25.3       ],
       [37.9       ],
       [35.9       ],
       [32.4       ],
       [30.4       ],
       [27.        ],
       [26.        ],
       [38.7       ],
       [45.6       ],
       [20.8       ],
       [36.1       ],
       [36.9       ],
       [36.6       ],
       [43.3       ],
       [40.5       ],
       [21.9       ],
       [35.5       ],
       [28.        ],
       [30.7       ],
       [36.6       ],
       [23.6       ],
       [32.3       ],
       [31.6       ],
       [35.8       ],
       [52.9       ],
       [21.        ],
       [39.7       ],
       [25.5       ],
       [24.8       ],
       [30.5       ],
       [32.9       ],
       [26.2       ],
       [39.4       ],
       [26.6       ],
       [29.5       ],
       [35.9       ],
       [34.1       ],
       [19.3       ],
       [30.5       ],
       [38.1       ],
       [23.5       ],
       [27.5       ],
       [31.6       ],
       [27.4       ],
       [26.8       ],
       [35.7       ],
       [25.6       ],
       [35.1       ],
       [35.1       ],
       [45.5       ],
       [30.8       ],
       [23.1       ],
       [32.7       ],
       [43.3       ],
       [23.6       ],
       [23.9       ],
       [47.9       ],
       [33.8       ],
       [31.2       ],
       [34.2       ],
       [39.9       ],
       [25.9       ],
       [25.9       ],
       [32.        ],
       [34.7       ],
       [36.8       ],
       [38.5       ],
       [28.7       ],
       [23.5       ],
       [21.8       ],
       [41.        ],
       [42.2       ],
       [31.2       ],
       [34.4       ],
       [27.2       ],
       [42.7       ],
       [30.4       ],
       [33.3       ],
       [39.9       ],
       [35.3       ],
       [36.5       ],
       [31.2       ],
       [29.8       ],
       [39.2       ],
       [38.5       ],
       [34.9       ],
       [34.        ],
       [27.6       ],
       [21.        ],
       [27.5       ],
       [32.8       ],
       [38.4       ],
       [32.45746367],
       [35.8       ],
       [34.9       ],
       [36.2       ],
       [39.2       ],
       [25.2       ],
       [37.2       ],
       [48.3       ],
       [43.4       ],
       [30.8       ],
       [20.        ],
       [25.4       ],
       [25.1       ],
       [24.3       ],
       [22.3       ],
       [32.3       ],
       [43.3       ],
       [32.        ],
       [31.6       ],
       [32.        ],
       [45.7       ],
       [23.7       ],
       [22.1       ],
       [32.9       ],
       [27.7       ],
       [24.7       ],
       [34.3       ],
       [21.1       ],
       [34.9       ],
       [32.        ],
       [24.2       ],
       [35.        ],
       [31.6       ],
       [32.9       ],
       [42.1       ],
       [28.9       ],
       [21.9       ],
       [25.9       ],
       [42.4       ],
       [35.7       ],
       [34.4       ],
       [42.4       ],
       [26.2       ],
       [34.6       ],
       [35.7       ],
       [27.2       ],
       [38.5       ],
       [18.2       ],
       [26.4       ],
       [45.3       ],
       [26.        ],
       [40.6       ],
       [30.8       ],
       [42.9       ],
       [37.        ],
       [32.45746367],
       [34.1       ],
       [40.6       ],
       [35.        ],
       [22.2       ],
       [30.4       ],
       [30.        ],
       [25.6       ],
       [24.5       ],
       [42.4       ],
       [37.4       ],
       [29.9       ],
       [18.2       ],
       [36.8       ],
       [34.3       ],
       [32.2       ],
       [33.2       ],
       [30.5       ],
       [29.7       ],
       [59.4       ],
       [25.3       ],
       [36.5       ],
       [33.6       ],
       [30.5       ],
       [21.2       ],
       [28.9       ],
       [39.9       ],
       [19.6       ],
       [37.8       ],
       [33.6       ],
       [26.7       ],
       [30.2       ],
       [37.6       ],
       [25.9       ],
       [20.8       ],
       [21.8       ],
       [35.3       ],
       [27.6       ],
       [24.        ],
       [21.8       ],
       [27.8       ],
       [36.8       ],
       [30.        ],
       [46.1       ],
       [41.3       ],
       [33.2       ],
       [38.8       ],
       [29.9       ],
       [28.9       ],
       [27.3       ],
       [33.7       ],
       [23.8       ],
       [25.9       ],
       [28.        ],
       [35.5       ],
       [35.2       ],
       [27.8       ],
       [38.2       ],
       [44.2       ],
       [42.3       ],
       [40.7       ],
       [46.5       ],
       [25.6       ],
       [26.1       ],
       [36.8       ],
       [33.5       ],
       [32.8       ],
       [28.9       ],
       [32.45746367],
       [26.6       ],
       [26.        ],
       [30.1       ],
       [25.1       ],
       [29.3       ],
       [25.2       ],
       [37.2       ],
       [39.        ],
       [33.3       ],
       [37.3       ],
       [33.3       ],
       [36.5       ],
       [28.6       ],
       [30.4       ],
       [25.        ],
       [29.7       ],
       [22.1       ],
       [24.2       ],
       [27.3       ],
       [25.6       ],
       [31.6       ],
       [30.3       ],
       [37.6       ],
       [32.8       ],
       [19.6       ],
       [25.        ],
       [33.2       ],
       [32.45746367],
       [34.2       ],
       [31.6       ],
       [21.8       ],
       [18.2       ],
       [26.3       ],
       [30.8       ],
       [24.6       ],
       [29.8       ],
       [45.3       ],
       [41.3       ],
       [29.8       ],
       [33.3       ],
       [32.9       ],
       [29.6       ],
       [21.7       ],
       [36.3       ],
       [36.4       ],
       [39.4       ],
       [32.4       ],
       [34.9       ],
       [39.5       ],
       [32.        ],
       [34.5       ],
       [43.6       ],
       [33.1       ],
       [32.8       ],
       [28.5       ],
       [27.4       ],
       [31.9       ],
       [27.8       ],
       [29.9       ],
       [36.9       ],
       [25.5       ],
       [38.1       ],
       [27.8       ],
       [46.2       ],
       [30.1       ],
       [33.8       ],
       [41.3       ],
       [37.6       ],
       [26.9       ],
       [32.4       ],
       [26.1       ],
       [38.6       ],
       [32.        ],
       [31.3       ],
       [34.3       ],
       [32.5       ],
       [22.6       ],
       [29.5       ],
       [34.7       ],
       [30.1       ],
       [35.5       ],
       [24.        ],
       [42.9       ],
       [27.        ],
       [34.7       ],
       [42.1       ],
       [25.        ],
       [26.5       ],
       [38.7       ],
       [28.7       ],
       [22.5       ],
       [34.9       ],
       [24.3       ],
       [33.3       ],
       [21.1       ],
       [46.8       ],
       [39.4       ],
       [34.4       ],
       [28.5       ],
       [33.6       ],
       [32.        ],
       [45.3       ],
       [27.8       ],
       [36.8       ],
       [23.1       ],
       [27.1       ],
       [23.7       ],
       [27.8       ],
       [35.2       ],
       [28.4       ],
       [35.8       ],
       [40.        ],
       [19.5       ],
       [41.5       ],
       [24.        ],
       [30.9       ],
       [32.9       ],
       [38.2       ],
       [32.5       ],
       [36.1       ],
       [25.8       ],
       [28.7       ],
       [20.1       ],
       [28.2       ],
       [32.4       ],
       [38.4       ],
       [24.2       ],
       [40.8       ],
       [43.5       ],
       [30.8       ],
       [37.7       ],
       [24.7       ],
       [32.4       ],
       [34.6       ],
       [24.7       ],
       [27.4       ],
       [34.5       ],
       [26.2       ],
       [27.5       ],
       [25.9       ],
       [31.2       ],
       [28.8       ],
       [31.6       ],
       [40.9       ],
       [19.5       ],
       [29.3       ],
       [34.3       ],
       [29.5       ],
       [28.        ],
       [27.6       ],
       [39.4       ],
       [23.4       ],
       [37.8       ],
       [28.3       ],
       [26.4       ],
       [25.2       ],
       [33.8       ],
       [34.1       ],
       [26.8       ],
       [34.2       ],
       [38.7       ],
       [21.8       ],
       [38.9       ],
       [39.        ],
       [34.2       ],
       [27.7       ],
       [42.9       ],
       [37.6       ],
       [37.9       ],
       [33.7       ],
       [34.8       ],
       [32.5       ],
       [27.5       ],
       [34.        ],
       [30.9       ],
       [33.6       ],
       [25.4       ],
       [35.5       ],
       [57.3       ],
       [35.6       ],
       [30.9       ],
       [24.8       ],
       [35.3       ],
       [36.        ],
       [24.2       ],
       [24.2       ],
       [49.6       ],
       [44.6       ],
       [32.3       ],
       [32.45746367],
       [33.2       ],
       [23.1       ],
       [28.3       ],
       [24.1       ],
       [46.1       ],
       [24.6       ],
       [42.3       ],
       [39.1       ],
       [38.5       ],
       [23.5       ],
       [30.4       ],
       [29.9       ],
       [25.        ],
       [34.5       ],
       [44.5       ],
       [35.9       ],
       [27.6       ],
       [35.        ],
       [38.5       ],
       [28.4       ],
       [39.8       ],
       [32.45746367],
       [34.4       ],
       [32.8       ],
       [38.        ],
       [31.2       ],
       [29.6       ],
       [41.2       ],
       [26.4       ],
       [29.5       ],
       [33.9       ],
       [33.8       ],
       [23.1       ],
       [35.5       ],
       [35.6       ],
       [29.3       ],
       [38.1       ],
       [29.3       ],
       [39.1       ],
       [32.8       ],
       [39.4       ],
       [36.1       ],
       [32.4       ],
       [22.9       ],
       [30.1       ],
       [28.4       ],
       [28.4       ],
       [44.5       ],
       [29.        ],
       [23.3       ],
       [35.4       ],
       [27.4       ],
       [32.        ],
       [36.6       ],
       [39.5       ],
       [42.3       ],
       [30.8       ],
       [28.5       ],
       [32.7       ],
       [40.6       ],
       [30.        ],
       [49.3       ],
       [46.3       ],
       [36.4       ],
       [24.3       ],
       [31.2       ],
       [39.        ],
       [26.        ],
       [43.3       ],
       [32.4       ],
       [36.5       ],
       [32.        ],
       [36.3       ],
       [37.5       ],
       [35.5       ],
       [28.4       ],
       [44.        ],
       [22.5       ],
       [32.9       ],
       [36.8       ],
       [26.2       ],
       [30.1       ],
       [30.4       ]])